language: c

sudo: false

cache:
  directories:
    - ~/.ghc
    - ~/.cabal

matrix:
  include:
    - env: CABALVER=1.24 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.8.4],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.2
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=1.24 GHCVER=7.8.4

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - case "$GHCVER" in
    "7.8.4") cabal install --only-dependencies ;;
    *)       cabal install --only-dependencies --enable-tests ;;
   esac
 - cabal install hpc-coveralls

script:
 - case "$CABALVER" in
    "7.8.4") cabal configure --enable-library-coverage -v2 -f dev ;;
    *)       cabal configure --enable-tests --enable-coverage -v2 -f dev ;;
   esac
 - travis_wait 40 cabal build
 - case "$GHCVER" in
    "7.8.4") true ;;
    *)       cabal test --show-details=always ;;
   esac
 - cabal sdist
 - cabal haddock | grep "100%" | wc -l | grep "6"

after_script:
 - export PATH=~/.cabal/bin:$PATH
 - hpc-coveralls --coverage-mode=StrictlyFullLines
                 --exclude-dir=tests
                 --exclude-dir=mustache-spec
                 tests mustache-spec

notifications:
  email: false
